// === LEVELS DEFINITIONS ===
// TODOs 7, 11, and 12 will require changes to this section
const LEVELS = [
  {
    name: "Level 1",
    speed: 3.5,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 450, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1050, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1650, y: groundY },
      { type: "enemy", kind: "bug", x: 700, y: groundY },
      { type: "enemy", kind: "bug", x: 1250, y: groundY },
      { type: "enemy", kind: "bug", x: 1850, y: groundY },
      { type: "powerup", kind: "healthUp", x: 584, y: groundY - 130 },
      { type: "powerup", kind: "healthUp", x: 1034, y: groundY - 155 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 500,
        y: groundY - 70,
        contactHealthChange: -5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 950,
        y: groundY - 95,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1750,
        y: groundY - 75,
      },

      { type: "goal", kind: "flag", x: 2200, y: groundY },
    ],
  },
  {
    name: "Level 2",
    speed: 4.5,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 400, y: groundY },
      { type: "obstacle", kind: "spikes", x: 850, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1250, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1700, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1450, y: groundY },
      { type: "enemy", kind: "bug", x: 600, y: groundY },
      { type: "enemy", kind: "bug", x: 1000, y: groundY },
      { type: "enemy", kind: "bug", x: 1400, y: groundY },
      { type: "enemy", kind: "bug", x: 1550, y: groundY },
      { type: "enemy", kind: "bug", x: 1650, y: groundY },
      { type: "powerup", kind: "healthUp", x: 534, y: groundY - 130 },
      { type: "powerup", kind: "healthUp", x: 884, y: groundY - 165 },
      { type: "powerup", kind: "healthUp", x: 1234, y: groundY - 140 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 450,
        y: groundY - 70,
        contactHealthChange: -5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 800,
        y: groundY - 105,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1150,
        y: groundY - 80,
        contactHealthChange: -10,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1500,
        y: groundY - 110,
      },

      { type: "goal", kind: "flag", x: 2350, y: groundY },
    ],
  },
  {
    name: "Level 3: The Final Challenge",
    speed: 5.5,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 350, y: groundY },
      { type: "obstacle", kind: "spikes", x: 750, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1150, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1550, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1950, y: groundY },
      { type: "obstacle", kind: "spikes", x: 2350, y: groundY },
      { type: "obstacle", kind: "spikes", x: 2700, y: groundY },
      { type: "enemy", kind: "bug", x: 500, y: groundY },
      { type: "enemy", kind: "bug", x: 900, y: groundY },
      { type: "enemy", kind: "bug", x: 1300, y: groundY },
      { type: "enemy", kind: "bug", x: 1750, y: groundY },
      { type: "enemy", kind: "bug", x: 2150, y: groundY },
      { type: "enemy", kind: "bug", x: 2600, y: groundY },
      { type: "powerup", kind: "healthUp", x: 484, y: groundY - 130 },
      { type: "powerup", kind: "healthUp", x: 834, y: groundY - 165 },
      { type: "powerup", kind: "healthUp", x: 1184, y: groundY - 140 },
      { type: "powerup", kind: "healthUp", x: 1534, y: groundY - 170 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 400,
        y: groundY - 70,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 750,
        y: groundY - 105,
        contactHealthChange: -5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1100,
        y: groundY - 80,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1450,
        y: groundY - 110,
        hp: 0,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1950,
        y: groundY - 90,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 2550,
        y: groundY - 85,
      },

      { type: "goal", kind: "flag", x: 3100, y: groundY },
    ],
  },
];

let currentLevel = LEVELS[0];
let currentLevelIndex = 0;
// === END LEVELS DEFINITIONS ===

// === DEFAULT VALUES FOR EACH "type" AND "kind" OF OBJECT (STUDENT-EDITABLE) ===
const DEFAULT_VALUES = {
  obstacle: {
    spikes: {
      imageUrl: "images/interactable/spikes.png",
      width: 48,
      height: 48,
      hitWidth: 40,
      hitHeight: 44,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: -20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: false,
    },
  },
  enemy: {
    bug: {
      imageUrl: "images/interactable/bug.png",
      width: 75,
      height: 75,
      hitWidth: 75,
      hitHeight: 75,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 75,
      contactHealthChange: -30,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 50,
      hp: 3,
      collect: false,
    },
  },
  powerup: {
    healthUp: {
      imageUrl: "images/interactable/health-up.png",
      width: 32,
      height: 32,
      hitWidth: 32,
      hitHeight: 32,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 32,
      contactHealthChange: +20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  goal: {
    flag: {
      imageUrl: "images/interactable/flag.png",
      width: 100,
      height: 100,
      hitWidth: 100,
      hitHeight: 100,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: 0,
      contactScoreChange: +100,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  platform: {
    basicPlatform: {
      imageUrl: "images/interactable/basic-platform.png",
      width: 200,
      height: 50,
      hitWidth: 200,
      hitHeight: 50,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 50,
      contactHealthChange: 0,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: Infinity,
      collect: false,
    },
  },
};
// === END DEFAULT VALUES ===
